### ISSUE TITLE
Consider SchXslt2 as transpiler for embedded assertions

### ISSUE THREAD

**Issue by dmj** [xmlcalabash/xmlcalabash3#73]
Happy to see SchXslt used for the embedded assertions. You might consider to replace it with SchXslt2 though. SchXslt is more or less in maintenance mode (will receive bugfixes), SchXslt2 is the XSLT 3 only implementation under active development.

https://sr.ht/~dmaus/schxslt2/

**Comment by ndw** [comment]
I was unaware. I'll make the switch asap.

**Comment by ndw** [comment]
Is there API documentation anywhere @dmj ? It's not obvious at a glance how to migrate to SchXslt2.

**Comment by ndw** [comment]
Maaayyyybbeeee it's as simple as running the Schematron through `transpile.xsl` to get a stylesheet and then processing the input with that stylesheet? Maybe?

**Comment by dmj** [comment]
> Maaayyyybbeeee it's as simple as running the Schematron through transpile.xsl to get a stylesheet and then processing the input with that stylesheet? Maybe?

Yes, that's all there is to it.

**Comment by ndw** [comment]
Done in `-alpha8`. Thanks again @dmj
