### ISSUE TITLE
Saxon EE configuration question

### ISSUE THREAD

**Issue by djbpitt** [xmlcalabash/xmlcalabash3#74]
https://docs.xmlcalabash.com/userguide/current/running.html advises us that running `java -jar xmlcalabash-app-3.0.0-alpha7.jar` uses Saxon HE by default, and that " if you have a Saxon-EE license, put the Saxon-EE jar file on the class path instead of the Saxon-HE jar file". But it also warns us that if we don't use the `-jar` option "the classpath contains both the XML Calabash jar file and all of the necessary dependencies". Unless I've misunderstood, it appears as if the two approaches (putting Saxon EE first but letting the Calabash *jar* file take care of the Calabash dependencies) cannot be combined; `java -cp /opt/saxon/saxon-ee-12.5.jar -jar xmlcalabash-app-3.0.0-alpha7.jar version --debug` finds EE, but although `java -cp /opt/saxon/saxon-ee-12.5.jar -jar xmlcalabash-app-3.0.0-alpha7.jar helloWorld.xpl` works, `java -cp /opt/saxon/saxon-ee-12.5.jar -jar xmlcalabash-app-3.0.0-alpha7.jar version --debug` alerts me that it's ignoring Saxon EE and running instead  with HE.

My question, then, is whether the only way to run with EE is to specify a `-cp` value that concatenates *all* of the jar files in the Calabash *lib* directory plus the main Calabash *jar* file and, in first position, the Saxon EE *jar* file? I'm hoping that there's an easier route that I've failed to understand, since the preceding seems like a rather laborious way to say "use EE instead of HE".

**Comment by djbpitt** [comment]
Answering my own question: The following works: `java -cp "/opt/saxon/saxon-ee-12.5.jar:/opt/calabash/xmlcalabash-3.0.0-alpha7/lib/*:/opt/calabash/xmlcalabash-3.0.0-alpha7/xmlcalabash-app-3.0.0-alpha7.jar" com.xmlcalabash.app.Main` 

I've left the issue open for the moment because neither the wildcard in the classpath nor the need to quote the classpath once it contained a wildcard was obvious to me (= user with no meaningful Java configuration experience). Problem solved for me, but I thought I should nonetheless mention it in case you anticipate other Java naïfs among Calabash users.

**Comment by djbpitt** [comment]
I'm using Java 21 and 23. Possibly related to https://github.com/oracle/graaljs/issues/834? If so, is there a non-tedious workaround?

**Comment by ndw** [comment]
I have a clumsy hack in mind. I have an even clumsier and more hacky solution that you can try today: copy your EE Saxon jar file over top of the HE one in `lib/`. Just don't tell anyone I suggested it 😄

**Comment by djbpitt** [comment]
@ndw Is this, then, a real Java issue, and not Yet Another User Error? And, with regard to The Hack That You Did Not Suggest, if someone were to copy the EE jar over the HE one, would there be an easy way to help it find the license file? Asking for a friend …

**Comment by ndw** [comment]
It's not user error. The trick where `-jar some.jar` uses the manifest in that jar file to look for additional files (like all the things I slung in `lib/`) doesn't work if you put that jar explicitly on a classpath. That's a feature, just an annoying one. 

I see the problem with the license file. There [some suggestions](https://www.saxonica.com/documentation12/index.html#!about/license/licensekey) in the docs. If the environment variable `SAXON_HOME` doesn't work, you can use the XML Calabash configuration file to point to a Saxon configuration file to point to your license file.

**Comment by ndw** [comment]
I believe this is [improved](https://docs.xmlcalabash.com/userguide/current/running.html#upgrading-saxon) in alpha8. I'm not sure how to do better in the short term. Let me know if you're still having trouble.

**Comment by djbpitt** [comment]
@ndw The hack that worked previously involved copying the EE jar file into the Calabash *lib* directory **and** naming it *Saxon-HE-12.5.jar*. If I’ve understood the new (alpha8) instructions correctly, I should now copy the EE jar into the Calabash *lib* directory under its original name, which is *saxon-ee-12.5.jar*, while also deleting the HE jar that is distributed with Calabash. When I do that, I see:

```
djb@Davids-Mac-mini ~ % xmlcalabash version
XML Calabash version 3.0.0-alpha8 (build 713c7df, 28 December 2024)
Running with Saxon HE version 12.5%
```

If I copy the EE *jar* over the HE one in the Calabash *lib* directory (that is, if the copy of the EE jar is called *Saxon-HE-12.5.jar*, as I did with the earlier alpha7 hack), Calabash also reports that it is using HE.  

I'm not sure how to understand this report: Calabash tells me it's using HE even when there is no HE *jar* file in the *lib* directory. Is there a way I can confirm whether Calabash is actually using my EE *jar* file or whether it will fail when I try to run an XSLT transformation because it will try to use an HE *jar* that it won’t be able to find?

**Comment by ndw** [comment]
This is a pet peeve of mine. Saxon EE without a license reports that it's HE. And it (mostly) behaves like HE. I'm to believe that historically this was a sensible thing to do. But this is not the first time I've seen it cause confusion. It's confused the living daylights out of me more than once.

I *think* what you've failed to do is setup `SAXON_HOME` to point to where your license is. Or you've failed to "export" that setting in your current shell.

I keep my license in `/Users/ndw/java` for no particular reason that I recall. Been that way for a decade at least.

Here's what I see:

```
$ unzip ~/Downloads/xmlcalabash-3.0.0-alpha8.zip
...
$ cd xmlcalabash-3.0.0-alpha8/
$ java -jar xmlcalabash-app-3.0.0-alpha8.jar version
XML Calabash version 3.0.0-alpha8 (build 713c7df, 28 December 2024)
Running with Saxon HE version 12.5
$ rm lib/Saxon-HE-12.5.jar
$ cp /some/random/place/Saxon-EE-12.5.jar lib/
$ java -jar xmlcalabash-app-3.0.0-alpha8.jar version
XML Calabash version 3.0.0-alpha8 (build 713c7df, 28 December 2024)
Running with Saxon HE version 12.5
$ export SAXON_HOME=/Users/ndw/java
$ java -jar xmlcalabash-app-3.0.0-alpha8.jar version
XML Calabash version 3.0.0-alpha8 (build 713c7df, 28 December 2024)
Running with Saxon EE version 12.5 (with a license)
```

Voilà

I will see if I can make the `version` command offer a bit more in the way of useful information.

Hope that helps. Let me know if it doesn't. I'll see about improving the docs further.

**Comment by djbpitt** [comment]
@ndw This is embarrassing! I had tested the `SAXON_HOME` environment variable successfully earlier, but apparently I neglected to write it into my *.zshrc*. Sigh. When I go back and do that, all is well:

```
djb@Davids-Mac-mini ~ % echo $SAXON_HOME
/opt/saxon
djb@Davids-Mac-mini ~ % ls -al /opt/calabash/xmlcalabash-3.0.0-alpha8/lib/*axo*
-rw-r--r--@ 1 root  staff  8073025 Dec 28 11:58 /opt/calabash/xmlcalabash-3.0.0-alpha8/lib/saxon-ee-12.5.jar
djb@Davids-Mac-mini ~ % java -jar /opt/calabash/xmlcalabash-3.0.0-alpha8/xmlcalabash-app-3.0.0-alpha8.jar version
XML Calabash version 3.0.0-alpha8 (build 713c7df, 28 December 2024)
Running with Saxon EE version 12.5 (with a license)%
```

More generally, I understand why it might be useful for Saxon EE, when run without a license, to report that the user can expect only HE functionality. With that said, "running with Saxon EE as HE" (or even "running with Saxon EE, unlicensed, as HE") might be a more useful diagnostic report than "running with Saxon HE". But that may be more of a Saxon matter than a Calabash one. Thank you again for the help!
